def source():
    return input("expr> ")


def run_000(): return eval(source())
def run_001(): return eval(source())
def run_002(): return eval(source())
def run_003(): return eval(source())
def run_004(): return eval(source())
def run_005(): return eval(source())
def run_006(): return eval(source())
def run_007(): return eval(source())
def run_008(): return eval(source())
def run_009(): return eval(source())
def run_010(): return eval(source())
def run_011(): return eval(source())
def run_012(): return eval(source())
def run_013(): return eval(source())
def run_014(): return eval(source())
def run_015(): return eval(source())
def run_016(): return eval(source())
def run_017(): return eval(source())
def run_018(): return eval(source())
def run_019(): return eval(source())
